apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "12345678"
  MYSQL_HOST: "apdev-rds-instance.abcdefghijkl.ap-northeast-2.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DBNAME: "dev"
  S3_BUCKET_NAME: "apdev-bucket-125"
