apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  role: KarpenterNodeRole-<클러스터이름>
  amiSelectorTerms:
    - alias: bottlerocket@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: <클러스터이름>
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: <클러스터이름>
